# Setup
title: 'Missing Semester'
url: https://afnom.github.io
domain: afnom.github.io

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: America/New_York

collections:
  '2019':
    output: false
  '2020':
    output: false
  '2023':
    output: true
  '2024':
    output: true
  '2025':
    output: true

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
